version: '3.8'
services:
  redisdb: 
    container_name: rediscontainerdb
    restart: always
    ports:
      - "6379:6379"
  rabbitmq:
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
  moviedb:
    container_name: moviedb
    restart: always
    ports:
      - "1444:1433"
    volumes:
      - moviedb_volume:/var/opt/mssql
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=1


